from zope.i18nmessageid import MessageFactory
_ = MessageFactory("plumi")

vocab_set = {}

taxonomy_sub_folder={'topic':'video_categories','genre':'video_genre','callouts':'submission_categories','countries':'video_countries'}

vocab_set['video_countries'] = (
         ('XX', _(' International')),
         ('BU', _('Bougainville')),
         ('TI', _('Tibet')),
         ('AQ', _('Antarctica')),
         ('HA', _('Hawaii')),
         ('WP', _('West Papua')),
         ('BN', _(u'Brunei Darussalam ')),
         ('MM', _(u'Myanmar ')),
         ('KH', _(u'Cambodia')),
         ('ID', _(u'Indonesia ')),
         ('LA', _(u'Lao People\'s Democratic Republic')),
         ('MY', _(u'Malaysia')),
         ('PH', _(u'Philippines ')),
         ('SG', _(u'Singapore ')),
         ('TH', _(u'Thailand')),
         ('VN', _(u'Viet Nam')),
         ('AQ', _(u'Antarctica')),
         ('AU', _(u'Australia ')),
         ('FJ', _(u'Fiji')),
         ('PF', _(u'French Polynesia')),
         ('GU', _(u'Guam')),
         ('HK', _(u'Hong Kong')),
         ('KI', _(u'Kiribati')),
         ('MH', _(u'Marshall Islands')),
         ('FM', _(u'Micronesia, Federated States Of ')),
         ('NZ', _(u'New Zealand ')),
         ('NR', _(u'Nauru ')),
         ('NC', _(u'New Caledonia ')),
         ('MP', _(u'Northern Mariana Islands')),
         ('PW', _(u'Palau ')),
         ('PG', _(u'Papua New Guinea')),
         ('PN', _(u'Pitcairn')),
         ('WS', _(u'Samoa ')),
         ('SB', _(u'Solomon Islands ')),
         ('TL', _(u'Timor-Leste')),
         ('TK', _(u'Tokelau ')),
         ('TO', _(u'Tonga ')),
         ('TV', _(u'Tuvalu')),
         ('VU', _(u'Vanuatu ')),
         ('CN', _(u'China ')),
         ('JP', _(u'Japan ')),
         ('KP', _(u'Korea, Democratic People\'s Republic Of')),
         ('KR', _(u'Korea, Republic Of')),
         ('MN', _(u'Mongolia')),
         ('TW', _(u'Taiwan')),
         ('BD', _(u'Bangladesh')),
         ('BT', _(u'Bhutan')),
         ('IN', _(u'India ')),
         ('MV', _(u'Maldives')),
         ('NP', _(u'Nepal ')),
         ('PK', _(u'Pakistan')),
         ('LK', _(u'Sri Lanka ')),
        )

vocab_set['video_categories'] = (
         ('poverty', _(u'Poverty / Development')),
         ('indigenous', _(u'Indigenous')),
         ('refugee', _(u'Refugee / Migration')),
         ('health', _(u'Health')),
         ('corporations', _(u'Corporations / Privatisation')),
         ('globalisation', _(u'Globalisation')),
         ('law', _(u'Law / Justice')),
         ('work', _(u'Work')),
         ('consumerism', _(u'Consumerism')),
         ('war', _(u'War / Peace')),
         ('human', _(u'Human Rights')),
         ('disability', _(u'Disability Rights')),
         ('gender', _(u'Gender / Sexuality')),
         ('race', _(u'Race')),
         ('religion', _(u'Religion')),
         ('art', _(u'Art / Culture')),
         ('internet', _(u'Internet')),
         ('media', _(u'Media')),
         ('activism', _(u'Activism')),
         ('politics', _(u'Politics')),
         ('education', _(u'Education')),
         ('biodiversity', _(u'Biodiversity')),
         ('climate', _(u'Climate Change')),
         ('conservation', _(u'Forests / Conservation')),
         ('nuclear', _(u'Nuclear')),
         ('sustainablity', _(u'Sustainability')),
         ('animal', _(u'Animal Rights')),
         ('water', _(u'Water')),
         ('biotech', _(u'Biotech')),
         ('civillib',_(u'Civil Liberties')),
        )
vocab_set['video_genre'] = (
         ('none', _(u'-- None --')),
         ('documentary', _(u'Documentary')),
         ('experimental', _(u'Experimental')),
         ('fiction', _(u'Fiction')),
         ('animation', _(u'Animation')),
         ('music', _(u'Music')),
         ('newsreport', _(u'News Report')),
        )
vocab_set['submission_categories'] = (
         ('none', _(u'----------------')),
         ('festival', _(u'Festival')),
         ('screening', _(u'Screening')),
         ('dvd', _(u'DVD')),
         ('production', _(u'Production')),
         ('conference', _(u'Conference')),
         ('workshop', _(u'Workshop')),
         ('crew', _(u'Crew')),
         ('competition', _(u'Competition')),
         ('artprize', _(u'Art Prize')),
         ('exhibition',_(u'Exhibition')),
         ('other', _(u'Other')),
        ) 
vocab_set['video_languages'] = (
        ('aa', _(u'Afar ')),
        ('ab', _(u'Abkhazian ')),
        ('af', _(u'Afrikaans ')),
        ('am', _(u'Amharic ')),
        ('ar', _(u'Arabic ')),
        ('as', _(u'Assamese ')),
        ('ay', _(u'Aymara ')),
        ('az', _(u'Azerbaijani ')),
        ('ba', _(u'Bashkir ')),
        ('be', _(u'Byelorussian ')),
        ('bg', _(u'Bulgarian ')),
        ('bh', _(u'Bihari ')),
        ('bi', _(u'Bislama ')),
        ('bn', _(u'Bengali;')),
        ('bo', _(u'Tibetan ')),
        ('br', _(u'Breton ')),
        ('ca', _(u'Catalan ')),
        ('co', _(u'Corsican ')),
        ('cs', _(u'Czech ')),
        ('cy', _(u'Welsh ')),
        ('da', _(u'Danish ')),
        ('de', _(u'German ')),
        ('dz', _(u'Bhutani ')),
        ('el', _(u'Greek ')),
        ('en', _(u'English ')),
        ('eo', _(u'Esperanto ')),
        ('es', _(u'Spanish ')),
        ('et', _(u'Estonian ')),
        ('eu', _(u'Basque ')),
        ('fa', _(u'Persian ')),
        ('fi', _(u'Finnish ')),
        ('fj', _(u'Fiji ')),
        ('fo', _(u'Faroese ')),
        ('fr', _(u'French ')),
        ('fy', _(u'Frisian ')),
        ('ga', _(u'Irish ')),
        ('gd', _(u'Scots')),
        ('gl', _(u'Galician ')),
        ('gn', _(u'Guarani ')),
        ('gu', _(u'Gujarati ')),
        ('ha', _(u'Hausa ')),
        ('he', _(u'Hebrew')),
        ('hi', _(u'Hindi ')),
        ('hr', _(u'Croatian ')),
        ('hu', _(u'Hungarian ')),
        ('hy', _(u'Armenian ')),
        ('ia', _(u'Interlingua ')),
        ('id', _(u'Indonesian')),
        ('ie', _(u'Interlingue ')),
        ('ik', _(u'Inupiak ')),
        ('is', _(u'Icelandic ')),
        ('it', _(u'Italian ')),
        ('iu', _(u'Inuktitut ')),
        ('ja', _(u'Japanese ')),
        ('jw', _(u'Javanese ')),
        ('ka', _(u'Georgian ')),
        ('kk', _(u'Kazakh ')),
        ('kl', _(u'Greenlandic ')),
        ('km', _(u'Cambodian ')),
        ('kn', _(u'Kannada ')),
        ('ko', _(u'Korean ')),
        ('ks', _(u'Kashmiri ')),
        ('ku', _(u'Kurdish ')),
        ('ky', _(u'Kirghiz ')),
        ('la', _(u'Latin ')),
        ('ln', _(u'Lingala ')),
        ('lo', _(u'Laothian ')),
        ('lt', _(u'Lithuanian ')),
        ('lv', _(u'Latvian')),
        ('mg', _(u'Malagasy ')),
        ('mi', _(u'Maori ')),
        ('mk', _(u'Macedonian ')),
        ('ml', _(u'Malayalam ')),
        ('mn', _(u'Mongolian ')),
        ('mo', _(u'Moldavian ')),
        ('mr', _(u'Marathi ')),
        ('ms', _(u'Malay ')),
        ('mt', _(u'Maltese ')),
        ('my', _(u'Burmese ')),
        ('na', _(u'Nauru ')),
        ('ne', _(u'Nepali ')),
        ('nl', _(u'Dutch ')),
        ('no', _(u'Norwegian ')),
        ('oc', _(u'Occitan ')),
        ('om', _(u'Afan')),
        ('or', _(u'Oriya ')),
        ('pa', _(u'Punjabi ')),
        ('pl', _(u'Polish ')),
        ('ps', _(u'Pashto')),
        ('pt', _(u'Portuguese ')),
        ('qu', _(u'Quechua ')),
        ('rm', _(u'Rhaeto-Romance ')),
        ('rn', _(u'Kirundi ')),
        ('ro', _(u'Romanian ')),
        ('ru', _(u'Russian ')),
        ('rw', _(u'Kinyarwanda ')),
        ('sa', _(u'Sanskrit ')),
        ('sd', _(u'Sindhi ')),
        ('sg', _(u'Sangho ')),
        ('sh', _(u'Serbo-Croatian ')),
        ('si', _(u'Sinhalese ')),
        ('sk', _(u'Slovak ')),
        ('sl', _(u'Slovenian ')),
        ('sm', _(u'Samoan ')),
        ('sn', _(u'Shona ')),
        ('so', _(u'Somali ')),
        ('sq', _(u'Albanian ')),
        ('sr', _(u'Serbian ')),
        ('ss', _(u'Siswati ')),
        ('st', _(u'Sesotho ')),
        ('su', _(u'Sundanese ')),
        ('sv', _(u'Swedish ')),
        ('sw', _(u'Swahili ')),
        ('ta', _(u'Tamil ')),
        ('te', _(u'Telugu ')),
        ('tg', _(u'Tajik ')),
        ('th', _(u'Thai ')),
        ('ti', _(u'Tigrinya ')),
        ('tk', _(u'Turkmen ')),
        ('tl', _(u'Tagalog ')),
        ('tn', _(u'Setswana ')),
        ('to', _(u'Tonga ')),
        ('tr', _(u'Turkish ')),
        ('ts', _(u'Tsonga ')),
        ('tt', _(u'Tatar ')),
        ('tw', _(u'Twi ')),
        ('ug', _(u'Uighur ')),
        ('uk', _(u'Ukrainian ')),
        ('ur', _(u'Urdu ')),
        ('uz', _(u'Uzbek ')),
        ('vi', _(u'Vietnamese ')),
        ('vo', _(u'Volapuk ')),
        ('wo', _(u'Wolof ')),
        ('xh', _(u'Xhosa ')),
        ('yi', _(u'Yiddish')),
        ('yo', _(u'Yoruba ')),
        ('za', _(u'Zhuang ')),
        ('zh', _(u'Chinese ')),
        ('zu', _(u'Zulu ')),
       ) 

